"""add user active

Revision ID: 110f6dcc8c3e
Revises: 6e012f1e00f4
Create Date: 2024-08-03 13:23:08.736857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110f6dcc8c3e'
down_revision = '6e012f1e00f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
